### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by Cookiemonster75** [godver3/cli_debrid#273]
Hello again. I am interested in testing the windows build. I have tried the exe but can't get anywhere with it. I am running windows 11. If I can help testing let me know. Cheers.

**Comment by godver3** [comment]
Hey Cookiemonster75 - sorry, the tagging is misleading. The windows build
isn’t ready yet, but hoping to get something going in the next couple days.
I’ll respond on this issue once it’s ready for testing - thanks!

**Comment by Cookiemonster75** [comment]
Cheers. I appreciate that. The project is really looking forward class.

**Comment by godver3** [comment]
@Cookiemonster75 The Windows version is now available under releases for testing:

https://github.com/godver3/cli_debrid/releases/download/v0.4.92/cli_debrid-0.4.92.exe

Thanks for your patience.

**Comment by godver3** [comment]
Let me know if you'd like to join the private Discord server for quick testing discussions - you can reach me at godver3 on Discord.

**Comment by Cookiemonster75** [comment]
Cheers boss. Thanks again for your work.
